spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.243.3.17:3306/bbs?characterEncoding=utf-8
    username: root
    password: Enjoylink$2017
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:static/,file:static/
imagepath: D:/bbsimages/
mybatis:
  type-aliases-package: com.bbs.domain
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    com.bbs.post.mapper: error